reformat clippy.ymk and clippy_bors.yml

diff --git a/.github/workflows/clippy_bors.yml b/.github/workflows/clippy_bors.yml
--- a/.github/workflows/clippy_bors.yml
+++ b/.github/workflows/clippy_bors.yml
@@ -8,7 +8,7 @@ on:
 
 env:
   RUST_BACKTRACE: 1
-  CARGO_TARGET_DIR: '${{ github.workspace }}/target'
+  CARGO_TARGET_DIR: "${{ github.workspace }}/target"
   NO_FMT_TEST: 1
 
 defaults:
@@ -20,168 +20,174 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
-      with:
-        github_token: "${{ secrets.github_token }}"
+      - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
+        with:
+          github_token: "${{ secrets.github_token }}"
 
-    - name: Checkout
-      uses: actions/checkout@v2.3.3
-      with:
-        ref: ${{ github.ref }}
+      - name: Checkout
+        uses: actions/checkout@v2.3.3
+        with:
+          ref: ${{ github.ref }}
 
-    # Run
-    - name: Check Changelog
-      run: |
-        MESSAGE=$(git log --format=%B -n 1)
-        PR=$(echo "$MESSAGE" | grep -o "#[0-9]*" | head -1 | sed -e 's/^#//')
-        output=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s "https://api.github.com/repos/rust-lang/rust-clippy/pulls/$PR" | \
-          python -c "import sys, json; print(json.load(sys.stdin)['body'])" | \
-          grep "^changelog: " | \
-          sed "s/changelog: //g")
-        if [[ -z "$output" ]]; then
-          echo "ERROR: PR body must contain 'changelog: ...'"
-          exit 1
-        elif [[ "$output" = "none" ]]; then
-          echo "WARNING: changelog is 'none'"
-        fi
-      env:
-        PYTHONIOENCODING: 'utf-8'
+      # Run
+      - name: Check Changelog
+        run: |
+          MESSAGE=$(git log --format=%B -n 1)
+          PR=$(echo "$MESSAGE" | grep -o "#[0-9]*" | head -1 | sed -e 's/^#//')
+          output=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s "https://api.github.com/repos/rust-lang/rust-clippy/pulls/$PR" | \
+            python -c "import sys, json; print(json.load(sys.stdin)['body'])" | \
+            grep "^changelog: " | \
+            sed "s/changelog: //g")
+          if [[ -z "$output" ]]; then
+            echo "ERROR: PR body must contain 'changelog: ...'"
+            exit 1
+          elif [[ "$output" = "none" ]]; then
+            echo "WARNING: changelog is 'none'"
+          fi
+        env:
+          PYTHONIOENCODING: "utf-8"
   base:
     needs: changelog
     strategy:
       matrix:
         os: [ubuntu-latest, windows-latest, macos-latest]
-        host: [x86_64-unknown-linux-gnu, i686-unknown-linux-gnu, x86_64-apple-darwin, x86_64-pc-windows-msvc]
+        host:
+          [
+            x86_64-unknown-linux-gnu,
+            i686-unknown-linux-gnu,
+            x86_64-apple-darwin,
+            x86_64-pc-windows-msvc,
+          ]
         exclude:
-        - os: ubuntu-latest
-          host: x86_64-apple-darwin
-        - os: ubuntu-latest
-          host: x86_64-pc-windows-msvc
-        - os: macos-latest
-          host: x86_64-unknown-linux-gnu
-        - os: macos-latest
-          host: i686-unknown-linux-gnu
-        - os: macos-latest
-          host: x86_64-pc-windows-msvc
-        - os: windows-latest
-          host: x86_64-unknown-linux-gnu
-        - os: windows-latest
-          host: i686-unknown-linux-gnu
-        - os: windows-latest
-          host: x86_64-apple-darwin
+          - os: ubuntu-latest
+            host: x86_64-apple-darwin
+          - os: ubuntu-latest
+            host: x86_64-pc-windows-msvc
+          - os: macos-latest
+            host: x86_64-unknown-linux-gnu
+          - os: macos-latest
+            host: i686-unknown-linux-gnu
+          - os: macos-latest
+            host: x86_64-pc-windows-msvc
+          - os: windows-latest
+            host: x86_64-unknown-linux-gnu
+          - os: windows-latest
+            host: i686-unknown-linux-gnu
+          - os: windows-latest
+            host: x86_64-apple-darwin
 
     runs-on: ${{ matrix.os }}
 
     # NOTE: If you modify this job, make sure you copy the changes to clippy.yml
     steps:
-    # Setup
-    - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
-      with:
-        github_token: "${{ secrets.github_token }}"
+      # Setup
+      - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
+        with:
+          github_token: "${{ secrets.github_token }}"
 
-    - name: Install dependencies (Linux-i686)
-      run: |
-        sudo dpkg --add-architecture i386
-        sudo apt-get update
-        sudo apt-get install gcc-multilib libssl-dev:i386 libgit2-dev:i386
-      if: matrix.host == 'i686-unknown-linux-gnu'
+      - name: Install dependencies (Linux-i686)
+        run: |
+          sudo dpkg --add-architecture i386
+          sudo apt-get update
+          sudo apt-get install gcc-multilib libssl-dev:i386 libgit2-dev:i386
+        if: matrix.host == 'i686-unknown-linux-gnu'
 
-    - name: Checkout
-      uses: actions/checkout@v2.3.3
+      - name: Checkout
+        uses: actions/checkout@v2.3.3
 
-    - name: Install toolchain
-      run: rustup show active-toolchain
+      - name: Install toolchain
+        run: rustup show active-toolchain
 
-    # Run
-    - name: Set LD_LIBRARY_PATH (Linux)
-      if: runner.os == 'Linux'
-      run: |
-        SYSROOT=$(rustc --print sysroot)
-        echo "LD_LIBRARY_PATH=${SYSROOT}/lib${LD_LIBRARY_PATH+:${LD_LIBRARY_PATH}}" >> $GITHUB_ENV
-    - name: Link rustc dylib (MacOS)
-      if: runner.os == 'macOS'
-      run: |
-        SYSROOT=$(rustc --print sysroot)
-        sudo mkdir -p /usr/local/lib
-        sudo find "${SYSROOT}/lib" -maxdepth 1 -name '*dylib' -exec ln -s {} /usr/local/lib \;
-    - name: Set PATH (Windows)
-      if: runner.os == 'Windows'
-      run: |
-        SYSROOT=$(rustc --print sysroot)
-        echo "$SYSROOT/bin" >> $GITHUB_PATH
+      # Run
+      - name: Set LD_LIBRARY_PATH (Linux)
+        if: runner.os == 'Linux'
+        run: |
+          SYSROOT=$(rustc --print sysroot)
+          echo "LD_LIBRARY_PATH=${SYSROOT}/lib${LD_LIBRARY_PATH+:${LD_LIBRARY_PATH}}" >> $GITHUB_ENV
+      - name: Link rustc dylib (MacOS)
+        if: runner.os == 'macOS'
+        run: |
+          SYSROOT=$(rustc --print sysroot)
+          sudo mkdir -p /usr/local/lib
+          sudo find "${SYSROOT}/lib" -maxdepth 1 -name '*dylib' -exec ln -s {} /usr/local/lib \;
+      - name: Set PATH (Windows)
+        if: runner.os == 'Windows'
+        run: |
+          SYSROOT=$(rustc --print sysroot)
+          echo "$SYSROOT/bin" >> $GITHUB_PATH
 
-    - name: Build
-      run: cargo build --features deny-warnings,internal-lints
+      - name: Build
+        run: cargo build --features deny-warnings,internal-lints
 
-    - name: Test
-      run: cargo test --features deny-warnings,internal-lints
+      - name: Test
+        run: cargo test --features deny-warnings,internal-lints
 
-    - name: Test clippy_lints
-      run: cargo test --features deny-warnings,internal-lints
-      working-directory: clippy_lints
+      - name: Test clippy_lints
+        run: cargo test --features deny-warnings,internal-lints
+        working-directory: clippy_lints
 
-    - name: Test rustc_tools_util
-      run: cargo test --features deny-warnings
-      working-directory: rustc_tools_util
+      - name: Test rustc_tools_util
+        run: cargo test --features deny-warnings
+        working-directory: rustc_tools_util
 
-    - name: Test clippy_dev
-      run: cargo test --features deny-warnings
-      working-directory: clippy_dev
+      - name: Test clippy_dev
+        run: cargo test --features deny-warnings
+        working-directory: clippy_dev
 
-    - name: Test cargo-clippy
-      run: ../target/debug/cargo-clippy
-      working-directory: clippy_workspace_tests
+      - name: Test cargo-clippy
+        run: ../target/debug/cargo-clippy
+        working-directory: clippy_workspace_tests
 
-    - name: Test cargo-clippy --fix
-      run: ../target/debug/cargo-clippy clippy --fix -Zunstable-options
-      working-directory: clippy_workspace_tests
+      - name: Test cargo-clippy --fix
+        run: ../target/debug/cargo-clippy clippy --fix -Zunstable-options
+        working-directory: clippy_workspace_tests
 
-    - name: Test clippy-driver
-      run: bash .github/driver.sh
-      env:
-        OS: ${{ runner.os }}
+      - name: Test clippy-driver
+        run: bash .github/driver.sh
+        env:
+          OS: ${{ runner.os }}
 
-    - name: Test cargo dev new lint
-      run: |
-        cargo dev new_lint --name new_early_pass --pass early
-        cargo dev new_lint --name new_late_pass --pass late
-        cargo check
-        git reset --hard HEAD
+      - name: Test cargo dev new lint
+        run: |
+          cargo dev new_lint --name new_early_pass --pass early
+          cargo dev new_lint --name new_late_pass --pass late
+          cargo check
+          git reset --hard HEAD
 
   integration_build:
     needs: changelog
     runs-on: ubuntu-latest
 
     steps:
-    # Setup
-    - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
-      with:
-        github_token: "${{ secrets.github_token }}"
+      # Setup
+      - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
+        with:
+          github_token: "${{ secrets.github_token }}"
 
-    - name: Checkout
-      uses: actions/checkout@v2.3.3
+      - name: Checkout
+        uses: actions/checkout@v2.3.3
 
-    - name: Install toolchain
-      run: rustup show active-toolchain
+      - name: Install toolchain
+        run: rustup show active-toolchain
 
-    # Run
-    - name: Build Integration Test
-      run: cargo test --test integration --features integration --no-run
+      # Run
+      - name: Build Integration Test
+        run: cargo test --test integration --features integration --no-run
 
-    # Upload
-    - name: Extract Binaries
-      run: |
-        DIR=$CARGO_TARGET_DIR/debug
-        rm $DIR/deps/integration-*.d
-        mv $DIR/deps/integration-* $DIR/integration
-        find $DIR ! -executable -o -type d ! -path $DIR | xargs rm -rf
-        rm -rf $CARGO_TARGET_DIR/release
+      # Upload
+      - name: Extract Binaries
+        run: |
+          DIR=$CARGO_TARGET_DIR/debug
+          rm $DIR/deps/integration-*.d
+          mv $DIR/deps/integration-* $DIR/integration
+          find $DIR ! -executable -o -type d ! -path $DIR | xargs rm -rf
+          rm -rf $CARGO_TARGET_DIR/release
 
-    - name: Upload Binaries
-      uses: actions/upload-artifact@v1
-      with:
-        name: target
-        path: target
+      - name: Upload Binaries
+        uses: actions/upload-artifact@v1
+        with:
+          name: target
+          path: target
 
   integration:
     needs: integration_build
@@ -190,55 +196,55 @@ jobs:
       max-parallel: 6
       matrix:
         integration:
-        - 'rust-lang/cargo'
-        # FIXME: re-enable once fmt_macros is renamed in RLS
-        # - 'rust-lang/rls'
-        - 'rust-lang/chalk'
-        - 'rust-lang/rustfmt'
-        - 'Marwes/combine'
-        - 'Geal/nom'
-        - 'rust-lang/stdarch'
-        - 'serde-rs/serde'
-        # FIXME: chrono currently cannot be compiled with `--all-targets`
-        # - 'chronotope/chrono'
-        - 'hyperium/hyper'
-        - 'rust-random/rand'
-        - 'rust-lang/futures-rs'
-        - 'rust-itertools/itertools'
-        - 'rust-lang-nursery/failure'
-        - 'rust-lang/log'
+          - "rust-lang/cargo"
+          # FIXME: re-enable once fmt_macros is renamed in RLS
+          # - 'rust-lang/rls'
+          - "rust-lang/chalk"
+          - "rust-lang/rustfmt"
+          - "Marwes/combine"
+          - "Geal/nom"
+          - "rust-lang/stdarch"
+          - "serde-rs/serde"
+          # FIXME: chrono currently cannot be compiled with `--all-targets`
+          # - 'chronotope/chrono'
+          - "hyperium/hyper"
+          - "rust-random/rand"
+          - "rust-lang/futures-rs"
+          - "rust-itertools/itertools"
+          - "rust-lang-nursery/failure"
+          - "rust-lang/log"
 
     runs-on: ubuntu-latest
 
     steps:
-    # Setup
-    - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
-      with:
-        github_token: "${{ secrets.github_token }}"
+      # Setup
+      - uses: rust-lang/simpleinfra/github-actions/cancel-outdated-builds@master
+        with:
+          github_token: "${{ secrets.github_token }}"
 
-    - name: Checkout
-      uses: actions/checkout@v2.3.3
+      - name: Checkout
+        uses: actions/checkout@v2.3.3
 
-    - name: Install toolchain
-      run: rustup show active-toolchain
+      - name: Install toolchain
+        run: rustup show active-toolchain
 
-    # Download
-    - name: Download target dir
-      uses: actions/download-artifact@v1
-      with:
-        name: target
-        path: target
+      # Download
+      - name: Download target dir
+        uses: actions/download-artifact@v1
+        with:
+          name: target
+          path: target
 
-    - name: Make Binaries Executable
-      run: chmod +x $CARGO_TARGET_DIR/debug/*
+      - name: Make Binaries Executable
+        run: chmod +x $CARGO_TARGET_DIR/debug/*
 
-    # Run
-    - name: Test ${{ matrix.integration }}
-      run: |
-        RUSTUP_TOOLCHAIN="$(rustup show active-toolchain | grep -o -E "nightly-[0-9]{4}-[0-9]{2}-[0-9]{2}")" \
-          $CARGO_TARGET_DIR/debug/integration
-      env:
-        INTEGRATION: ${{ matrix.integration }}
+      # Run
+      - name: Test ${{ matrix.integration }}
+        run: |
+          RUSTUP_TOOLCHAIN="$(rustup show active-toolchain | grep -o -E "nightly-[0-9]{4}-[0-9]{2}-[0-9]{2}")" \
+            $CARGO_TARGET_DIR/debug/integration
+        env:
+          INTEGRATION: ${{ matrix.integration }}
 
   # These jobs doesn't actually test anything, but they're only used to tell
   # bors the build completed, as there is no practical way to detect when a
